version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticket-postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticketdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ticket-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ticket-network
    environment:
      # Override for Docker internal networking
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ticket-network:
    driver: bridge